# Generated by Django 5.2.1 on 2025-10-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("pptx", "PowerPoint"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
