# Generated by Django 5.2.7 on 2025-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="vectorstore_path",
            field=models.CharField(null=True),
        ),
    ]
